export const UPDATE_TEXT_COLOR = 'UPDATE_TEXT_COLOR';
export const UPDATE_FONT_SIZE = 'UPDATE_FONT_SIZE';
export const TOGGLE_IS_FONT_BOLD = 'TOGGLE_IS_FONT_BOLD';
export const UPDATE_BACKGROUND_COLOR = 'UPDATE_BACKGROUND_COLOR';
export const UPDATE_ACCESSIBILITY_LEVEL = 'UPDATE_ACCESSIBILITY_LEVEL';
